export const ApiRoutes = {
    Chat: '/api/chat',
    Suggestions: '/api/suggestions',
    Analyze: '/api/analyze',
    Generate: '/api/generate',
    Extract: '/api/extract',
    LinkedInAuth: '/api/linkedin/auth',
    LinkedInStatus: '/api/linkedin/status',
    LinkedInDisconnect: '/api/linkedin/disconnect',
    LinkedInPublish: '/api/linkedin/publish',
    LinkedInSwitch: '/api/linkedin/switch',
}

export const Routes = {
    Home: '',
    Tool: '/#tool',
    AllFeatures: '/#all-features',
    HowItWorks: '/#how-it-works',
    Faqs: '/#faqs',
    Blog: '/blog',
    BlogPost: (slug: string) => `/blog/${slug}`,
    Changelog: '/changelog',
    Preview: '/preview',
    Compare: '/compare',
    ComparePost: (slug: string) => `/compare/${slug}`,
    Embed: '/embed',
    EmbedSection: '/#embed',
    Dashboard: '/dashboard',
    DashboardEditor: (draftId?: string) => (draftId ? `/dashboard/editor?draft=${draftId}` : '/dashboard/editor'),
    DashboardPosts: '/dashboard',
    DashboardCalendar: '/dashboard/calendar',
    DashboardStrategy: '/dashboard/strategy',
    DashboardBranding: '/dashboard/branding',
    DashboardSettings: '/dashboard/settings',
}
