export const ApiRoutes = {
    Chat: '/api/chat',
    Suggestions: '/api/suggestions',
    Analyze: '/api/analyze',
    AnalyticsInsights: '/api/analytics/insights',
    AnalyticsImportLinkedIn: '/api/analytics/import-linkedin',
    Generate: '/api/generate',
    Extract: '/api/extract',
    LinkPreview: '/api/link-preview',
    LinkedInAuth: '/api/linkedin/auth',
    LinkedInAnalyticsAuth: '/api/linkedin/analytics/auth',
    LinkedInStatus: '/api/linkedin/status',
    LinkedInDisconnect: '/api/linkedin/disconnect',
    LinkedInPublish: '/api/linkedin/publish',
    LinkedInSwitch: '/api/linkedin/switch',
}

export const Routes = {
    Home: '',
    Tool: '/#tool',
    AllFeatures: '/#all-features',
    HowItWorks: '/#how-it-works',
    Faqs: '/#faqs',
    Blog: '/blog',
    BlogPost: (slug: string) => `/blog/${slug}`,
    Changelog: '/changelog',
    Preview: '/preview',
    Compare: '/compare',
    ComparePost: (slug: string) => `/compare/${slug}`,
    Formatter: '/formatter',
    Generator: '/linkedin-post-generator',
    LinkPreview: '/linkedin-link-preview',
    Vorschau: '/linkedin-vorschau',
    Embed: '/embed',
    EmbedSection: '/#embed',
    Dashboard: '/dashboard',
    DashboardEditor: (draftId?: string) => (draftId ? `/dashboard/editor?draft=${draftId}` : '/dashboard/editor'),
    DashboardPosts: '/dashboard',
    DashboardCalendar: '/dashboard/calendar',
    DashboardAnalytics: '/dashboard/analytics',
    DashboardStrategy: '/dashboard/strategy',
    DashboardBranding: '/dashboard/branding',
    DashboardSettings: '/dashboard/settings',
}
