// ---------------------------------------------------------------------------
// Curated icon set for carousel slides. A fixed registry (not the full Lucide
// export) keeps the bundle lean per the icon-import convention, and gives the
// icon picker a stable, named list.
// ---------------------------------------------------------------------------

import {
    AlertTriangleIcon,
    ArrowRightIcon,
    ArrowUpRightIcon,
    AwardIcon,
    BarChart3Icon,
    BellIcon,
    BookmarkIcon,
    BriefcaseIcon,
    CalendarIcon,
    CheckCircle2Icon,
    CheckIcon,
    ChevronRightIcon,
    ClockIcon,
    DollarSignIcon,
    EyeIcon,
    FlameIcon,
    GiftIcon,
    GlobeIcon,
    HeartIcon,
    InfoIcon,
    KeyIcon,
    LightbulbIcon,
    LineChartIcon,
    LinkIcon,
    LockIcon,
    MailIcon,
    MapPinIcon,
    MessageCircleIcon,
    MinusIcon,
    PhoneIcon,
    PieChartIcon,
    PlayIcon,
    PlusIcon,
    QuoteIcon,
    RocketIcon,
    SearchIcon,
    SettingsIcon,
    Share2Icon,
    ShieldIcon,
    SparklesIcon,
    StarIcon,
    TagIcon,
    TargetIcon,
    ThumbsUpIcon,
    TrendingUpIcon,
    TrophyIcon,
    UserIcon,
    UsersIcon,
    XIcon,
    ZapIcon,
    type LucideIcon,
} from 'lucide-react'

export const CAROUSEL_ICONS: Record<string, LucideIcon> = {
    'arrow-right': ArrowRightIcon,
    'arrow-up-right': ArrowUpRightIcon,
    'chevron-right': ChevronRightIcon,
    'check': CheckIcon,
    'check-circle': CheckCircle2Icon,
    'x': XIcon,
    'plus': PlusIcon,
    'minus': MinusIcon,
    'star': StarIcon,
    'heart': HeartIcon,
    'thumbs-up': ThumbsUpIcon,
    'zap': ZapIcon,
    'flame': FlameIcon,
    'sparkles': SparklesIcon,
    'lightbulb': LightbulbIcon,
    'rocket': RocketIcon,
    'target': TargetIcon,
    'trophy': TrophyIcon,
    'award': AwardIcon,
    'trending-up': TrendingUpIcon,
    'bar-chart': BarChart3Icon,
    'pie-chart': PieChartIcon,
    'line-chart': LineChartIcon,
    'quote': QuoteIcon,
    'message-circle': MessageCircleIcon,
    'share': Share2Icon,
    'bookmark': BookmarkIcon,
    'eye': EyeIcon,
    'users': UsersIcon,
    'user': UserIcon,
    'briefcase': BriefcaseIcon,
    'clock': ClockIcon,
    'calendar': CalendarIcon,
    'dollar-sign': DollarSignIcon,
    'alert-triangle': AlertTriangleIcon,
    'info': InfoIcon,
    'link': LinkIcon,
    'mail': MailIcon,
    'phone': PhoneIcon,
    'map-pin': MapPinIcon,
    'globe': GlobeIcon,
    'search': SearchIcon,
    'settings': SettingsIcon,
    'lock': LockIcon,
    'key': KeyIcon,
    'shield': ShieldIcon,
    'gift': GiftIcon,
    'tag': TagIcon,
    'bell': BellIcon,
    'play': PlayIcon,
}

export const CAROUSEL_ICON_NAMES = Object.keys(CAROUSEL_ICONS)

export function getIcon(name: string): LucideIcon {
    return CAROUSEL_ICONS[name] ?? SparklesIcon
}
